name: 'Stockroom deployment'
description: 'Deploy WP theme/plugin to a self hosted Stockroom'
author: 'wpstockroom'
branding:
  icon: 'package'
  color: 'green'
outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.deployment.outputs.zip-path }}
runs:
  using: 'composite'
  steps:
    - id: deployment
      run: ${{ github.action_path }}/deploy.sh
      shell: bash
